name: Run Tests and Upload Artifacts

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover > test-output.txt

    - name: Upload test output
      uses: actions/upload-artifact@v3
      with:
        name: test-output
        path: test-output.txt
